package model;

import kotlinx.coroutines.flow.Flow

interface Model<TReq : ModelRequest<*>, TRes : ModelResponse<*>> {
    /**
     * Executes a method call to the AI model.
     * @param request the request object to be sent to the AI model
     * @return the response from the AI model
     */
    suspend fun call(request: TReq): TRes
}


interface StreamingModel<TReq : ModelRequest<*>, TResChunk : ModelResponse<*>> {
    /**
     * Executes a method call to the AI model.
     * @param request the request object to be sent to the AI model
     * @return the streaming response from the AI model
     */
	suspend fun stream(request: TReq): Flow<TResChunk>
}

interface ModelRequest<T> {

    /**
     * Retrieves the instructions or input required by the AI model.
     * @return the instructions or input required by the AI model
     */
    val instructions: T // required input

    /**
     * Retrieves the customizable options for AI model interactions.
     * @return the customizable options for AI model interactions
     */
    val options: ModelOptions?

}

interface ModelOptions


interface ModelResponse<T : ModelResult<*>> {
    /**
     * Retrieves the result of the AI model.
     * @return the result generated by the AI model
     */
    val result: T

    /**
     * Retrieves the list of generated outputs by the AI model.
     * @return the list of generated outputs
     */
    val results: List<T>

    /**
     * Retrieves the response metadata associated with the AI model's response.
     * @return the response metadata
     */
    val responseMetadata: ResponseMetadata
}

interface ResponseMetadata{

	object NULL : ResponseMetadata

}

interface ModelResult<T> {
    /**
     * Retrieves the output generated by the AI model.
     * @return the output generated by the AI model
     */
    val output: T

    /**
     * Retrieves the metadata associated with the result of an AI model.
     * @return the metadata associated with the result
     */
    val resultMetadata: ResultMetadata

}

interface ResultMetadata{

	object NULL : ResultMetadata

}



