package io.kamo.ktor.client.ai.core.model


interface ModelResponse<T : ModelResult<*>> {

    /**
     * Retrieves the result of the AI model.
     * @return the result generated by the AI model
     */
    val result: T

    /**
     * Retrieves the list of generated outputs by the AI model.
     * @return the list of generated outputs
     */
    val results: List<T>

    /**
     * Retrieves the response metadata associated with the AI model's response.
     * @return the response metadata
     */
    val responseMetadata: ResponseMetadata

}

interface ResponseMetadata{

    object NULL : ResponseMetadata

}
